### PR TITLE
Display env if not on production

### PR DESCRIPTION
**Pull request by bfcoder**
Displays at the top of the page which env you are currently in.

image

image

### CODE REVIEW

**Comment by jbasdf** [comment]
Do we want it to be so large and in your face? Maybe we move it to a smaller div in the upper right or bottom right? I would also be fine with it just adding a meta tag to the page. Sometimes adding new html elements to the page will introduce differences that affect testing.

**Comment by bfcoder** [comment]
I wanted it to be obvious what env you are in. If you want it smaller maybe we can have Brandon design a "ribbon" that could go over the top right corner. Or something small like that.

**Comment by bfcoder** [comment]
Or we could just tone down the size of the element too.

**Comment by jbasdf** [comment]
LGTM

**Pull request merged**
